services:
  postgres:
    image: postgres:14
    container_name: gamestore-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gamestore
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - gamestore-network
 
  gamestore:
    image: ${DOCKER_REGISTRY-}gamestore
    build:
      context: .
      dockerfile: GameStore/Dockerfile
    container_name: gamestore-webapp
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=gamestore;Username=postgres;Password=postgres
      - Email__Host=smtp.gmail.com
      - Email__Port=587
      - Email__Sender=bebaccoun@gmail.com
      - Email__Username=bebaccoun@gmail.com
      - Email__Password=postgres
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    restart: always
    networks:
      - gamestore-network

networks:
  gamestore-network:
    driver: bridge

volumes:
  postgres-data: