version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: gamestore-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gamestore
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - gamestore-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gamestore"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  minio:
    image: minio/minio:latest
    container_name: gamestore-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    networks:
      - gamestore-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  gamestore:
    image: gamestore:latest
    build:
      context: .
      dockerfile: GameStore/Dockerfile
    container_name: gamestore-webapp
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=gamestore;Username=postgres;Password=postgres;Pooling=true;Minimum Pool Size=10;Maximum Pool Size=100;
      - Email__Host=smtp.gmail.com
      - Email__Port=587
      - Email__Sender=levwerlop@gmail.com
      - Email__Username=levwerlop@gmail.com
      - Email__Password=xxhnbnbdqnmtitov
      - TelegramBot__Token=7515132156:AAGirNJH-cpOkikSv0DAzKZIsLLEZ6xs3rQ
      - TelegramBot__ChatIds=5192243288,641673534
      - Storage__UseMinIO=true
      - MinIO__Endpoint=minio:9000
      - MinIO__AccessKey=minioadmin
      - MinIO__SecretKey=minioadmin
      - MinIO__BucketName=gamestore-images
      - MinIO__UseSSL=false
      - MinIO__PublicUrl=http://localhost:9000
      - BaseUrl=http://localhost:8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - gamestore-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gamestore-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - gamestore-network
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  gamestore-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local
  pgadmin-data:
    driver: local