services:
  postgres:
    image: postgres:14
    container_name: gamestore-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gamestore
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
 
  gamestore:
    image: ${DOCKER_REGISTRY-}gamestore
    build:
      context: .
      dockerfile: GameStore/Dockerfile
    container_name: gamestore-webapp
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=gamestore;Username=postgres;Password=postgres
      - Email__Host=smtp.gmail.com
      - Email__Port=587
      - Email__Sender=bebaccoun@gmail.com
      - Email__Username=bebaccoun@gmail.com
      - Email__Password=urvylockngtvzvbt
    ports:
      - "8080:8081"
    restart: always

volumes:
  postgres-data: